<?php

return [
    [
        'name' => 'Mr. Ghulam Murtaza',
        'email' => 'ghulam.murtaza@vitanova.org',
        'designation' => 'CEO & President',
        'details' => 'Center for Agricultural Biochemistry and Biotechnology - CABB',
        'unit_name' => 'Leadership Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/mr-ghulam-murtaza.jpeg',
    ],
    [
        'name' => 'Dr. M. Shahzad Zafar',
        'email' => 'shahzad.zafar@vitanova.org',
        'designation' => 'Senior Vice President',
        'details' => 'Shenzhen University, China',
        'unit_name' => 'Leadership Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-m-shahzad-zafar.jpeg',
    ],
    [
        'name' => 'Miss. Hafsa Sarfraz',
        'email' => 'hafsa.sarfraz@vitanova.org',
        'designation' => 'Vice President',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Leadership Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/miss-hafsa-sarfraz.jpeg',
    ],
    [
        'name' => 'Nupur Akter',
        'email' => 'nupur.akhter@vitanova.org',
        'designation' => 'Head of Collaborations',
        'details' => 'University of Science and Technology Chittagong, Bangladesh',
        'unit_name' => 'Leadership Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/nupur-akter.png',
    ],
    [
        'name' => 'Aisha',
        'email' => 'aisha@vitanova.org',
        'designation' => 'General Secretary',
        'details' => 'University of Sindh, Pakistan',
        'unit_name' => 'Leadership Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/aisha.jpeg',
    ],
    [
        'name' => 'Ruqia',
        'email' => 'ruqia@vitanova.org',
        'designation' => 'Record Keeping Secretary',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Secretariat Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/ruqia.jpeg',
    ],
    [
        'name' => 'Dr. Alveena Zahra',
        'email' => 'alveena.zahra@vitanova.org',
        'designation' => 'Peer Mentor',
        'details' => 'Jinnah Woman University Karachi, Pakistan',
        'unit_name' => 'Secretariat Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-alveena-zahra.jpeg',
    ],
    [
        'name' => 'Dr. Wazir Ali',
        'email' => 'wazir.ali@vitanova.org',
        'designation' => 'Community Outreach Partner',
        'details' => 'Shaheed Benazir Bhutto University, Shaheed Benazirabad, Pakistan',
        'unit_name' => 'Secretariat Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-wazir-ali.png',
    ],
    [
        'name' => 'Dr. Aitaj Ashgarova',
        'email' => 'aitaj.ashgarova@vitanova.org',
        'designation' => 'Public Speaker & Coordinator',
        'details' => 'Scientific Research Institute of Fruit and Tea Growing, Azerbaijan',
        'unit_name' => 'Secretariat Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-aitaj-ashgarova.jpeg',
    ],
    [
        'name' => 'Dr. Mouna',
        'email' => 'mouna@vitanova.org',
        'designation' => 'Research Coordinator',
        'details' => 'Hassan II University of Casablanca, Morocco',
        'unit_name' => 'Secretariat Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-mouna.jpeg',
    ],
    [
        'name' => 'Shakeela Anjum',
        'email' => 'shakeela.anjum@vitanova.org',
        'designation' => 'Secretariat Coordinator',
        'details' => 'University of Baltistan, Pakistan',
        'unit_name' => 'Secretariat Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/shakeela-anjum.png',
    ],
    [
        'name' => 'Ayesha Nazir',
        'email' => 'ayesha.nazir@vitanova.org',
        'designation' => 'Media Relations Officer',
        'details' => 'Bahaudin Zakriya University Multan, Pakistan',
        'unit_name' => 'Media Relations Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/ayesha-nazir.png',
    ],
    [
        'name' => 'Susan Aestino',
        'email' => 'susan.aestino@vitanova.org',
        'designation' => 'Graphic Designer',
        'details' => 'VitaNova International Alliance for Sciences',
        'unit_name' => 'Media Relations Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/susan-aestino.jpeg',
    ],
    [
        'name' => 'Aleeshbah Amir',
        'email' => 'aleeshbah.amir@vitanova.org',
        'designation' => 'Graphic Designer',
        'details' => 'National University of Medical Sciences',
        'unit_name' => 'Media Relations Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/aleeshbah-amir.jpeg',
    ],
    [
        'name' => 'Philip Anthony',
        'email' => 'philip.anthony@vitanova.org',
        'designation' => 'Graphic Designer',
        'details' => 'Biotechnology Department, Federal University Dutse',
        'unit_name' => 'Media Relations Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/philip-anthony.jpeg',
    ],
    [
        'name' => 'Zainab Shahid',
        'email' => 'zainab.shahid@vitanova.org',
        'designation' => 'Graphic Designer',
        'details' => 'Quid e Azam University, Islamabad, Pakistan',
        'unit_name' => 'Media Relations Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/zainab-shahid.jpeg',
    ],
    [
        'name' => 'Wajeeha Ahmed Khattak',
        'email' => 'wajeeha.khattak@vitanova.org',
        'designation' => 'Volunteer Graphic Designer',
        'details' => 'Fazaia Degree College, ARF PAC Kamra',
        'unit_name' => 'Media Relations Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/wajeeha-ahmed-khattak.jpeg',
    ],
    [
        'name' => 'Rabia Soomro',
        'email' => 'rabia.soomro@vitanova.org',
        'designation' => 'Director IT Unit',
        'details' => 'Sukkur IBA University',
        'unit_name' => 'IT Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/rabia-soomro.jpeg',
    ],
    [
        'name' => 'Areeba Yasir',
        'email' => 'areeba.yasir@vitanova.org',
        'designation' => 'Deputy Director',
        'details' => 'Fatima Jinnah Woman University Rawalpindi',
        'unit_name' => 'IT Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/areeba-yasir.png',
    ],
    [
        'name' => 'Usman Sarwar',
        'email' => 'usman.sarwar@vitanova.org',
        'designation' => 'Systems & Integration Coordinator',
        'details' => 'Sukkur IBA University',
        'unit_name' => 'IT Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/usman-sarwar.jpeg',
    ],
    [
        'name' => 'Muhammad Bilal',
        'email' => 'bilal.fiaz@vitanova.org',
        'designation' => 'Backend Operations Developer',
        'details' => 'Government College University Faisalabad',
        'unit_name' => 'IT Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/muhammad-bilal.png',
    ],
    [
        'name' => 'Sibgha Mursaleen',
        'email' => 'sibgha.mursaleen@vitanova.org',
        'designation' => 'Digital Platforms Coordinator',
        'details' => 'Sukkur IBA University',
        'unit_name' => 'IT Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/sibgha-mursaleen.jpeg',
    ],
    [
        'name' => 'Sajia Ashfaq',
        'email' => 'sajia.ashfaq@vitanova.org',
        'designation' => 'UX & Interface Coordinator',
        'details' => 'Jinnah University for Women, Karachi',
        'unit_name' => 'IT Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/sajia-ashfaq.jpeg',
    ],
    [
        'name' => 'Dr. Muhammad Ahmad',
        'email' => 'muhammad.ahmad@vitanova.org',
        'designation' => 'Research Projects Manager',
        'details' => 'China Agriculture University, Beijing, China',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-muhammad-ahmad.png',
    ],
    [
        'name' => 'Elnara Mutelim',
        'email' => 'elnara.mutelim@vitanova.org',
        'designation' => 'Head of Researchers',
        'details' => 'Scientific Research Institute of Fruit and Tea Growing, Azerbaijan',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/elnara-mutelim.png',
    ],
    [
        'name' => 'Rafia Noor ul Ain',
        'email' => 'rafia.noor@vitanova.org',
        'designation' => 'Research Content Writer',
        'details' => 'Arid Agriculture University, Rawalpindi, Pakistan',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/rafia-noor-ul-ain.png',
    ],
    [
        'name' => 'Babar Ali',
        'email' => 'babar.ali@vitanova.org',
        'designation' => 'Research Project Leader',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/babar-ali.png',
    ],
    [
        'name' => 'Sabahat Noor',
        'email' => 'sabahat.noor@vitanova.org',
        'designation' => 'Researcher',
        'details' => 'Rawalpindi Women University, Pakistan',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/sabahat-noor.jpeg',
    ],
    [
        'name' => 'Hina Fatima',
        'email' => 'hina.fatima@vitanova.org',
        'designation' => 'Researcher',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/hina-fatima.png',
    ],
    [
        'name' => 'Dr. Syed Hassan',
        'email' => 'syed.hassan@vitanova.org',
        'designation' => 'Researcher',
        'details' => 'University of Malakand, Balochistan',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-syed-hassan.png',
    ],
    [
        'name' => 'Amina Rafique',
        'email' => 'amina.rafique@vitanova.org',
        'designation' => 'Graduate Student (Biotechnology)',
        'details' => 'School of Biochemistry and Biotechnology, University of the Punjab,
                            Lahore, Pakistan',
        'unit_name' => 'Policy & Research Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/amina-rafique.jpeg',
    ],
    [
        'name' => 'Toufique',
        'email' => 'toufique@vitanova.org',
        'designation' => 'Senior Technical Content Write',
        'details' => 'Sindh Agriculture University, Tandojam, Pakistan',
        'unit_name' => 'Content Writing Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/toufique.jpeg',
    ],
    [
        'name' => 'Hina Sarwar',
        'email' => 'hina.sarwar@vitanova.org',
        'designation' => 'Content Writer',
        'details' => 'University of Narowal',
        'unit_name' => 'Content Writing Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/hina-sarwar.jpeg',
    ],
    [
        'name' => 'Hafsa Noor',
        'email' => 'hafsa.noor@vitanova.org',
        'designation' => 'Content Writer',
        'details' => 'Women University Multan, Pakistan',
        'unit_name' => 'Content Writing Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/hafsa-noor.jpeg',
    ],
    [
        'name' => 'Mansoor ul Haq',
        'email' => 'mansoor.haq@vitanova.org',
        'designation' => 'Deputy Director Social Media',
        'details' => 'Abdul Wali khan University, KPK, Pakistan',
        'unit_name' => 'Social Media Handling Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/mansoor-ul-haq.jpeg',
    ],
    [
        'name' => 'Arooj Fatima',
        'email' => 'arooj.fatima@vitanova.org',
        'designation' => 'Technical Manager',
        'details' => 'University of Central Punjab',
        'unit_name' => 'Social Media Handling Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/arooj-fatima.jpeg',
    ],
    [
        'name' => 'Noshaba Hassan',
        'email' => 'noshaba.hassan@vitanova.org',
        'designation' => 'Director Social Media',
        'details' => 'Women University Multan, Pakistan',
        'unit_name' => 'Social Media Handling Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/noshaba-hassan.jpeg',
    ],
    [
        'name' => 'Maryam Shahzadi',
        'email' => 'maryam.shahzadi@vitanova.org',
        'designation' => 'Assistant Manager',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Social Media Handling Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/maryam-shahzadi.jpeg',
    ],
    [
        'name' => 'Pirah Arif',
        'email' => 'pirah.arif@vitanova.org',
        'designation' => 'Assistant Manager',
        'details' => 'IBA Sukkur University, Sindh',
        'unit_name' => 'Social Media Handling Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/pirah-arif.jpeg',
    ],
    [
        'name' => 'Riya Jamshid',
        'email' => 'riya.jamshid@vitanova.org',
        'designation' => 'SEO Manager',
        'details' => 'University of Central Punjab, Pakistan',
        'unit_name' => 'Social Media Handling Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/riya-jamshid.jpeg',
    ],
    [
        'name' => 'Sheharyaar Farid',
        'email' => 'shehryar.farid@vitanova.org',
        'designation' => 'Scholarship Advisor',
        'details' => 'University of Galway, Ireland',
        'unit_name' => 'Scholarship Guidance Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/sheharyaar-farid.jpeg',
    ],
    [
        'name' => 'Kashif Ali',
        'email' => 'kashif.ali@vitanova.org',
        'designation' => 'Danube AgriFood Management Erasmus Mundus Program',
        'details' => 'Hungarian University of Agriculture and Life Sciences, Hungary &
                            University of Zagreb, Croatia',
        'unit_name' => 'Scholarship Guidance Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/kashif-ali.jpeg',
    ],
    [
        'name' => 'Dr. Ghulam Murtaza',
        'email' => 'ghulam.murtaza.scholar@vitanova.org',
        'designation' => 'Scholarship Advisor',
        'details' => 'Chinese Academy of Sciences, China',
        'unit_name' => 'Scholarship Guidance Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/dr-ghulam-murtaza.jpeg',
    ],
    [
        'name' => 'Abdullah Shoukat',
        'email' => 'abdullah.shoukat@vitanova.org',
        'designation' => 'MS Smart Agriculture',
        'details' => 'Atatürk üniversitesi Türkiye',
        'unit_name' => 'Scholarship Guidance Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/abdullah-shoukat.jpeg',
    ],
    [
        'name' => 'Abdul Hafeez',
        'email' => 'abdul.hafeez@vitanova.org',
        'designation' => 'MS Ecology',
        'details' => 'Northeast Normal University, China',
        'unit_name' => 'Scholarship Guidance Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/abdul-hafeez.jpeg',
    ],
    [
        'name' => 'Romesa Sajid',
        'email' => 'romesa.sajid@vitanova.org',
        'designation' => 'Marketing Manager',
        'details' => 'Air University, Islamabad, Pakistan',
        'unit_name' => 'Event Organizing & Planning Team',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/romesa-sajid.jpeg',
    ],
    [
        'name' => 'Rimsha Zahir Ali Shah',
        'email' => 'rimsha.zahir@vitanova.org',
        'designation' => 'Public Speaker & Host',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Event Organizing & Planning Team',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/rimsha-zahir-ali-shah.png',
    ],
    [
        'name' => 'Neha Aas Muhammad',
        'email' => 'neha.aas@vitanova.org',
        'designation' => 'Technical Event Manager',
        'details' => 'Govt. College University, Faisalabad, Pakistan',
        'unit_name' => 'Event Organizing & Planning Team',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/neha-aas-muhammad.png',
    ],
    [
        'name' => 'Iqra Faisal',
        'email' => 'iqra.faisal@vitanova.org',
        'designation' => 'Email Manager',
        'details' => 'Quid-I-Azam University, Islamabad',
        'unit_name' => 'Event Organizing & Planning Team',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/iqra-faisal.jpeg',
    ],
    [
        'name' => 'Yusra',
        'email' => 'yusra@vitanova.org',
        'designation' => 'Academic Coordinator',
        'details' => 'Fatima Jinnah Woman University',
        'unit_name' => 'Event Organizing & Planning Team',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/yusra.png',
    ],
    [
        'name' => 'Rozia Gul',
        'email' => 'rozia.gul@vitanova.org',
        'designation' => 'Event Coordinator',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Event Organizing & Planning Team',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/rozia-gul.jpeg',
    ],
    [
        'name' => 'Hira Khalid',
        'email' => 'hira.khalid@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'Liaqat University of Health and Medical Sciences',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Asma Ahmed',
        'email' => 'asma.ahmed@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'Quid-I-Azam University, Islamabad, Pakistan',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Zahra Batool',
        'email' => 'zahra.batool@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'University of Lahore',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Maryam Hayat',
        'email' => 'maryam.hayat@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'Bahaudin Zakriya University, Multan',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Eman Tariq',
        'email' => 'eman.tariq@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'Fatima Jinnah Woman University, Rawalpindi',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Adil Rasool',
        'email' => 'adil.rasool@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'University of Agriculture Faisalabad, Pakistan',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Ibrahim Buhari Yunusa',
        'email' => 'ibrahim.buhari@vitanova.org',
        'designation' => 'Nigeria International Coordinator',
        'details' => 'The Punjab University',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Ibrahim Zakari Ubale',
        'email' => 'ibrahim.zakari@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'Federal Dutse University, Nigeria',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Mujahid Khan',
        'email' => 'mujahid.khan@vitanova.org',
        'designation' => 'Lead Ambassador',
        'details' => 'University of Kohat, KPK, Pakistan',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Fathima Zanooja',
        'email' => 'fathima.zanooja@vitanova.org',
        'designation' => 'Sri Lanka Coordinator',
        'details' => 'The Punjab University',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => null,
    ],
    [
        'name' => 'Gulzar Ali',
        'email' => 'gulzar.ali@vitanova.org',
        'designation' => 'Chemist | Co-Lead Ambassador, UoS Chapter',
        'details' => 'Dr. M.A. Kazi Institute of Chemistry, University of Sindh',
        'unit_name' => 'Global Lead Ambassador Unit',
        'contact' => null,
        'address' => null,
        'profile_picture' => 'uploads/user-pictures/gulzar-ali.jpeg',
    ],
];